server.port=${PORT:8080}
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate

spring.h2.console.enabled=false

alphavantage.apikey=${ALPHAVANTAGE_APIKEY}
coinmarketcap.apikey=${COINMARKETCAP_APIKEY}
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
app.oauth2.frontend-redirect-uri=https://finance-portfolio-front-2.vercel.app/dashboard
api.security.token.secret=${API_SECURITY_TOKEN_SECRET}